category-list: [services]

# Privacy Policy and Terms of Service page
state: Utah

# Custom Navbar Colors
navbar-colors:
  bg: "#rgba(255, 255, 255, 1)"
  menu_color: "#000000"

# Custom button
btn-custom-primary:
  text-color: "#ffffff"
  bg: "#000000"
  border-color: "#000000"
  hover-text-color: "#ffffff"
  hover-bg: "#3f3f3f"
  hover-border-color: "#3f3f3f"

btn-custom-secondary:
  text-color: "#000000"
  bg: "#ffffff"
  border-color: "#ffffff"
  hover-text-color: "#000000"
  hover-bg: "#dddddd"
  hover-border-color: "#dddddd"

btn-border-radius: "0px"

collections:
  projects:
    output: true
    permalink: /project/:slug