title: "Wooley Art"
url: "https://wooleyart.com" 
logo: logo-wooley-art.png
logo-width: 130
tagline: Art Inspired by the Golden Age of Gaming
description: Discover a nostalgic journey through illustrated wonders and relive the golden age of gaming with our collection of game art.
phone: (385) 469-2233
author: Wooley
tagline: Game Art

google_analytics: G-D0SHHPXVR7

social:
  name: Wooley
  links:
    - https://www.facebook.com/profile.php?id=100092839737022
    - https://www.instagram.com/wooley_art/

# Local Business Schema
schema_type: LocalBusiness
# name: Same as title above
# image: Same as logo above
# telephone: Same as phone above
priceRange: "$"
address:
  city: "Salt Lake City"
  state: "Utah"
  country: "USA"
  postalCode: "84101"
hours:
  dayOfWeek: "Monday-Friday"
# url: Same as url above

collections:
  products:
    output: true
    permalink: /products/:slug
  posters:
    output: true
    permalink: /posters/:slug