font_settings:
  font_embed: "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;700&family=Mulish:wght@300;400;500;700&display=swap" 
  title_font: 'Mulish'
  body_font: 'Inter'

# Custom Navbar Colors
navbar_colors:
  bg: "rgba(255, 255, 255, .96)"
  menu_color: "#000000"
  menu_hover_color: "#000000"
  active_color: "#000000"
  menu_color: "#000000"
  brand_menu_color: "#000000"
  brand_menu_hover_color: "#000000"

navbar_spacing:
  padding_top: 24px
  padding_bottom: 24px;

# Custom button
btn-custom-primary:
  text-color: "#ffffff"
  bg: "#000000"
  border-color: "#000000"
  hover-text-color: "#ffffff"
  hover-bg: "#3f3f3f"
  hover-border-color: "#3f3f3f"

btn-custom-secondary:
  text-color: "#000000"
  bg: "#ffffff"
  border-color: "#ffffff"
  hover-text-color: "#000000"
  hover-bg: "#dddddd"
  hover-border-color: "#dddddd"

btn-border-radius: "0px"

# Background color for the call to action box
cta:
  bg: "linear-gradient(155deg, rgba(69,56,133,1) 0%, rgba(35,55,89,0.6) 100%);"

# Background color for the form submission box 
form: 
  bg: "#229155"

social_settings:
  facebook_url: 'https://www.facebook.com/profile.php?id=100092839737022'
  twitter_url: ''
  instagram_url: 'https://www.instagram.com/wooley_art/'
  youtube_url: ''
  medium_url: ''
  dribbble_url: ''
  github_url: ''
  linkedin_url: ''

# Local Business Schema
schema:
  # name: Same as title above
  # image: Same as logo above
  # telephone: Same as phone above
  priceRange: "$"
  address:
    city: "Salt Lake City"
    state: "Utah"
    country: "USA"
    postalCode: "84101"
  hours:
    dayOfWeek: "Monday-Friday"
  # url: Same as url above
# End Schema